"""tablas_iniciales

Revision ID: b74c0c44479c
Revises: 
Create Date: 2025-04-07 11:44:48.102249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b74c0c44479c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fonemas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('letra', sa.String(length=10), nullable=False),
    sa.Column('ruta_audio', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fonemas_id'), 'fonemas', ['id'], unique=False)
    op.create_table('lecturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_libro', sa.String(length=100), nullable=False),
    sa.Column('autor', sa.String(length=100), nullable=False),
    sa.Column('capitulo', sa.Integer(), nullable=True),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lecturas_id'), 'lecturas', ['id'], unique=False)
    op.create_table('audios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transcripcion', sa.String(length=200), nullable=False),
    sa.Column('ruta_audio', sa.String(length=255), nullable=False),
    sa.Column('lectura_id', sa.Integer(), nullable=True),
    sa.Column('fonema_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fonema_id'], ['fonemas.id'], ),
    sa.ForeignKeyConstraint(['lectura_id'], ['lecturas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audios_id'), 'audios', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audios_id'), table_name='audios')
    op.drop_table('audios')
    op.drop_index(op.f('ix_lecturas_id'), table_name='lecturas')
    op.drop_table('lecturas')
    op.drop_index(op.f('ix_fonemas_id'), table_name='fonemas')
    op.drop_table('fonemas')
    # ### end Alembic commands ###
